'use strict';
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const PORT = Number(process.env.PORT || 3000);
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const DATA_FILE = path.join(DATA_DIR, 'state.json');
const MAX_MESSAGE = Number(process.env.MAX_MESSAGE_LENGTH || 500);
const DEFAULT_MAX = Number(process.env.DEFAULT_MAX_USERS || 10000);
const ROOM_RATE = Number(process.env.ROOM_PUBLISH_PER_SECOND || 5);
const MIME = { '.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.json':'application/json; charset=utf-8' };

fs.mkdirSync(DATA_DIR, { recursive:true });
let state = fs.existsSync(DATA_FILE) ? JSON.parse(fs.readFileSync(DATA_FILE, 'utf8')) : { events:[], users:[], messages:[], bans:[] };
state.events ||= []; state.users ||= []; state.messages ||= []; state.bans ||= [];
const sessions = new Map();
const guestTokens = new Map();
const streams = new Map();
const roomRate = new Map();
const userRate = new Map();
let writeTimer;
const save = () => { clearTimeout(writeTimer); writeTimer = setTimeout(() => { const tmp=DATA_FILE+'.tmp'; fs.writeFileSync(tmp, JSON.stringify(state)); fs.renameSync(tmp, DATA_FILE); }, 40); };
const id = () => crypto.randomBytes(12).toString('hex');
const secretEqual = (a,b) => { const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||'')); return x.length===y.length&&crypto.timingSafeEqual(x,y); };
const color = (s,fallback) => /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(String(s||''))?String(s):fallback;
const logoUrl = s => { try { const u=new URL(String(s||'')); return u.protocol==='https:'?u.toString():''; } catch { return ''; } };
const slugify = s => String(s||'event').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'event';
const hash = (pass, salt=crypto.randomBytes(16).toString('hex')) => ({ salt, hash:crypto.scryptSync(pass,salt,64).toString('hex') });
const safeUser = u => ({ id:u.id,email:u.email,role:u.role,active:u.active!==false });
if (!state.users.some(u=>u.role==='owner')) {
  const email=(process.env.ADMIN_EMAIL||'admin@example.com').toLowerCase();
  const password=process.env.ADMIN_PASSWORD;
  if(!password||password.length<12) throw Error('Set ADMIN_PASSWORD to a unique password of at least 12 characters.');
  state.users.push({id:id(),email,role:'owner',active:true,...hash(password)}); save();
}
function send(res,status,data,headers={}) { res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}); res.end(JSON.stringify(data)); }
function cookie(req,name) { const s=req.headers.cookie||''; const part=s.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'=')); return part?decodeURIComponent(part.slice(name.length+1)):''; }
function auth(req, role) { const sid=cookie(req,'sid'); const sess=sessions.get(sid); if (!sess||sess.expires<Date.now()) { if(sid)sessions.delete(sid); return null; } const u=state.users.find(x=>x.id===sess.userId&&x.active!==false); if (!u || (role==='moderator'&&!['owner','moderator'].includes(u.role)) || (role==='stage'&&!['owner','moderator','stage'].includes(u.role))) return null; return u; }
function eventAuth(req,e,role='moderator') { const u=auth(req,role); return u&&(u.role==='owner'||e.moderators.includes(u.id))?u:null; }
async function body(req) { let s=''; for await (const c of req) { s+=c; if(s.length>30000) throw Error('Request too large'); } return s?JSON.parse(s):{}; }
function eventBySlug(slug) { return state.events.find(e=>e.slug===slug); }
function publicEvent(e) { return {id:e.id,slug:e.slug,title:e.title,mode:e.mode,capacity:e.capacity,chatEnabled:e.chatEnabled!==false,chatTypes:e.chatTypes||'both',languages:e.languages||['nl','en'],branding:e.branding,active:e.active,createdAt:e.createdAt}; }
function eventStreams(slug) { if(!streams.has(slug)) streams.set(slug,new Set()); return streams.get(slug); }
function broadcast(slug, kind, data, audience='all') { const payload=`event: ${kind}\ndata: ${JSON.stringify(data)}\n\n`; for(const c of eventStreams(slug)) { if(audience==='all'||c.role===audience||c.role==='owner') { try{c.res.write(payload);}catch{} } } }
function recent(slug, n=60) { return state.messages.filter(m=>m.slug===slug&&m.visibility==='public'&&m.status==='published').slice(-n); }
function messageEvent(m) { return {id:m.id,slug:m.slug,type:m.type,text:m.text,author:m.author,status:m.status,createdAt:m.createdAt,language:m.language||'nl',sourceId:m.sourceId||null}; }
function countConnections(slug) { return [...eventStreams(slug)].filter(c=>c.role==='guest').length; }
function addMessage(m) { state.messages.push(m); if(state.messages.length>100000) state.messages=state.messages.slice(-100000); save(); }
function sanitize(s, max=MAX_MESSAGE) { return String(s||'').replace(/[<>\u0000-\u001f\u007f]/g,' ').trim().slice(0,max); }
const server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://localhost');
  res.setHeader('x-content-type-options','nosniff');
  res.setHeader('referrer-policy','same-origin');
  res.setHeader('content-security-policy',`default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; img-src 'self' data: https:; frame-ancestors ${process.env.FRAME_ANCESTORS||'*'}`);
  if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type'});return res.end();}
  try {
    if(url.pathname==='/health') return send(res,200,{ok:true,connections:[...streams.values()].reduce((a,s)=>a+s.size,0),events:state.events.length});
    if(url.pathname==='/api/login'&&req.method==='POST') { const b=await body(req),email=String(b.email||'').toLowerCase(),u=state.users.find(x=>x.email===email&&x.active!==false); if(!u||!crypto.timingSafeEqual(Buffer.from(hash(String(b.password||''),u.salt).hash,'hex'),Buffer.from(u.hash,'hex'))) return send(res,401,{error:'E-mailadres of wachtwoord klopt niet'}); const sid=id()+id(); sessions.set(sid,{userId:u.id,expires:Date.now()+12*3600000}); const secure=req.headers['x-forwarded-proto']==='https'?' Secure;':''; return send(res,200,{user:safeUser(u)},{'set-cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200;${secure}`}); }
    if(url.pathname==='/api/logout'&&req.method==='POST'){sessions.delete(cookie(req,'sid'));return send(res,200,{ok:true},{'set-cookie':'sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
    if(url.pathname==='/api/me'&&req.method==='GET'){const u=auth(req);return u?send(res,200,{user:safeUser(u)}):send(res,401,{error:'Log in'});}
    if(url.pathname==='/api/events'&&req.method==='GET'){const u=auth(req);if(!u)return send(res,401,{error:'Log in'});return send(res,200,{events:state.events.filter(e=>u.role==='owner'||e.moderators.includes(u.id)).map(publicEvent)});}
    if(url.pathname==='/api/events'&&req.method==='POST'){const u=auth(req,'moderator');if(!u)return send(res,401,{error:'Geen toegang'});const b=await body(req);const title=sanitize(b.title,100)||'Nieuw evenement';let slug=slugify(b.slug||title);if(state.events.some(e=>e.slug===slug))slug+='-'+id().slice(0,4);const e={id:id(),slug,title,mode:'moderated',capacity:Math.min(20000,Math.max(1,Number(b.capacity)||DEFAULT_MAX)),active:true,chatEnabled:true,chatTypes:['public','private','both'].includes(b.chatTypes)?b.chatTypes:'both',languages:['nl','en'],branding:{primary:color(b.primary,'#57c5a5'),background:color(b.background,'#0b1220'),logo:logoUrl(b.logo)},createdAt:new Date().toISOString(),moderators:[u.id]};state.events.push(e);save();return send(res,201,{event:publicEvent(e)});}
    let match=url.pathname.match(/^\/api\/events\/([^/]+)(?:\/(.*))?$/);
    if(match){const slug=decodeURIComponent(match[1]),action=match[2]||'',e=eventBySlug(slug);if(!e||!e.active)return send(res,404,{error:'Evenement niet gevonden'});
      if(!action&&req.method==='GET')return send(res,200,{event:publicEvent(e)});
      if(action==='join'&&req.method==='POST'){const b=await body(req);if(e.chatEnabled===false)return send(res,403,{error:'Chat is uitgeschakeld'});const active=countConnections(slug);if(active>=e.capacity)return send(res,429,{error:'De maximale capaciteit van deze chat is bereikt.'});const participantId=String(b.participantId||'').slice(0,80);if(participantId&&state.bans.some(x=>x.slug===slug&&x.participantId===participantId))return send(res,403,{error:'Je hebt geen toegang tot deze chat'});const name=sanitize(b.name,40)||'Gast';const language=String(b.language||'nl').slice(0,8);const token=id()+id();guestTokens.set(token,{slug,name,participantId,language,createdAt:Date.now()});return send(res,200,{token,name,event:publicEvent(e),history:recent(slug)});}
      if(action==='stream'&&req.method==='GET'){const token=url.searchParams.get('token')||'';const guest=guestTokens.get(token);const u=auth(req,'stage');const access=url.searchParams.get('access')||'';const tokenValid=e.stageToken&&secretEqual(access,e.stageToken)&&Date.now()<e.stageAccessExpires;const role=guest&&guest.slug===slug?'guest':(u&&u.role!=='stage'&&eventAuth(req,e)?'moderator':(u&&u.role==='stage'&&eventAuth(req,e,'stage')?'stage':(tokenValid?'stage':null)));if(!role)return send(res,401,{error:'Sessie verlopen'});if(role==='guest'&&countConnections(slug)>=e.capacity)return send(res,429,{error:'De maximale capaciteit van deze chat is bereikt.'});res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache, no-transform','connection':'keep-alive','x-accel-buffering':'no'});let history=role==='guest'?recent(slug).filter(m=>m.language==='*'||m.language===guest.language):role==='stage'?state.messages.filter(m=>m.slug===slug&&m.status==='stage').slice(-30):recent(slug);res.write(`event: ready\ndata: ${JSON.stringify({connections:countConnections(slug),capacity:e.capacity,history})}\n\n`);const c={res,role,participantId:guest?.participantId};eventStreams(slug).add(c);const ping=setInterval(()=>{try{res.write(': ping\n\n')}catch{}},20000);req.on('close',()=>{clearInterval(ping);eventStreams(slug).delete(c);});return;}
      if(action==='messages'&&req.method==='POST'){const b=await body(req),token=String(b.token||''),g=guestTokens.get(token);if(!g||g.slug!==slug)return send(res,401,{error:'Sessie verlopen'});if(e.chatEnabled===false)return send(res,403,{error:'Chat is uitgeschakeld'});if(g.participantId&&state.bans.some(x=>x.slug===slug&&x.participantId===g.participantId))return send(res,403,{error:'Je hebt geen toegang tot deze chat'});if(e.mode==='readonly')return send(res,403,{error:'Chat staat op alleen-lezen'});const text=sanitize(b.text);if(!text)return send(res,400,{error:'Typ eerst een bericht'});const now=Date.now(),key=g.participantId||token,last=userRate.get(key)||0;if(now-last<5000)return send(res,429,{error:'Wacht even voordat je weer iets stuurt'});userRate.set(key,now);const privateOnly=e.chatTypes==='private';const kind=privateOnly?'private':(b.kind==='private'&&e.chatTypes==='both'?'private':'public');const lang=String(b.language||g.language||'nl').slice(0,8);const m={id:id(),slug,text,author:g.name,participantId:g.participantId||'',language:lang,type:kind==='private'?'private':'question',visibility:'private',status:'pending',createdAt:new Date().toISOString()};addMessage(m);broadcast(slug,'inbox',messageEvent(m),'moderator');return send(res,201,{ok:true,status:m.status});}
      const mod=eventAuth(req,e);
      if(action==='messages'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Geen toegang'});return send(res,200,{messages:state.messages.filter(m=>m.slug===slug).slice(-500)});}
      if(action==='settings'&&req.method==='PATCH'){if(!mod)return send(res,401,{error:'Geen toegang'});const b=await body(req);if(b.title)e.title=sanitize(b.title,100);if(['open','moderated','readonly'].includes(b.mode))e.mode=b.mode;if(Number.isFinite(Number(b.capacity)))e.capacity=Math.max(1,Math.min(20000,Number(b.capacity)));if(typeof b.chatEnabled==='boolean')e.chatEnabled=b.chatEnabled;if(['public','private','both'].includes(b.chatTypes))e.chatTypes=b.chatTypes;if(Array.isArray(b.languages))e.languages=b.languages.map(x=>String(x).slice(0,8)).slice(0,10);if(b.branding)e.branding={...e.branding,primary:color(b.branding.primary,e.branding.primary),background:color(b.branding.background,e.branding.background),logo:logoUrl(b.branding.logo)};save();broadcast(slug,'settings',publicEvent(e));return send(res,200,{event:publicEvent(e)});}
      const op=action.match(/^messages\/([^/]+)\/(publish|reject|stage|delete)$/);
      if(op&&req.method==='POST'){if(!mod)return send(res,401,{error:'Geen toegang'});const m=state.messages.find(x=>x.id===op[1]&&x.slug===slug);if(!m)return send(res,404,{error:'Bericht niet gevonden'});const act=op[2],b=await body(req);if(act==='publish'){const now=Date.now(),recentTimes=(roomRate.get(slug)||[]).filter(t=>now-t<1000);if(recentTimes.length>=ROOM_RATE)return send(res,429,{error:'De publicatie is tijdelijk afgeremd; probeer zo opnieuw'});roomRate.set(slug,[...recentTimes,now]);m.status='published';m.visibility='public';if(b.allLanguages)m.language='*';m.publishedAt=new Date().toISOString();broadcast(slug,'public',messageEvent(m));}if(act==='reject'){m.status='rejected';broadcast(slug,'inbox',messageEvent(m),'moderator');}if(act==='delete'){m.status='deleted';m.visibility='private';broadcast(slug,'remove',{id:m.id});}if(act==='stage'){m.status='stage';m.visibility='private';broadcast(slug,'stage',messageEvent(m),'stage');}save();return send(res,200,{message:messageEvent(m)});}
      if(action==='messages/private'&&req.method==='POST'){if(!mod)return send(res,401,{error:'Geen toegang'});const b=await body(req),text=sanitize(b.text),m=state.messages.find(x=>x.id===b.messageId&&x.slug===slug);if(!m||!m.participantId||!text)return send(res,400,{error:'Bericht kan niet privé worden beantwoord'});const reply={id:id(),slug,text,author:mod.email,type:'private-reply',visibility:'private',status:'private',targetParticipantId:m.participantId,createdAt:new Date().toISOString()};addMessage(reply);for(const c of eventStreams(slug))if(c.role==='guest'&&c.participantId===m.participantId)c.res.write(`event: private\ndata: ${JSON.stringify(messageEvent(reply))}\n\n`);return send(res,201,{message:messageEvent(reply)});}
      if(action==='ban'&&req.method==='POST'){if(!mod)return send(res,401,{error:'Geen toegang'});const b=await body(req),m=state.messages.find(x=>x.id===b.messageId&&x.slug===slug);if(!m?.participantId)return send(res,400,{error:'Deelnemer niet gevonden'});if(!state.bans.some(x=>x.slug===slug&&x.participantId===m.participantId))state.bans.push({slug,participantId:m.participantId,by:mod.email,at:new Date().toISOString()});for(const c of eventStreams(slug))if(c.role==='guest'&&c.participantId===m.participantId){try{c.res.write(`event: banned\ndata: {}\n\n`);c.res.end()}catch{}eventStreams(slug).delete(c)}save();return send(res,200,{ok:true});}
      if(action==='stage'&&req.method==='POST'){if(!mod)return send(res,401,{error:'Geen toegang'});const b=await body(req),text=sanitize(b.text);if(!text)return send(res,400,{error:'Bericht is leeg'});const m={id:id(),slug,text,author:mod.email,type:b.type==='cue'?'cue':'stage',visibility:'private',status:'stage',createdAt:new Date().toISOString()};addMessage(m);broadcast(slug,'stage',messageEvent(m),'stage');return send(res,201,{message:messageEvent(m)});}
      if(action==='stage-access'&&req.method==='POST'){if(!mod)return send(res,401,{error:'Geen toegang'});e.stageToken=crypto.randomBytes(24).toString('base64url');e.stageAccessExpires=Date.now()+12*3600000;save();return send(res,200,{url:`/stage/${slug}?access=${e.stageToken}`,expiresAt:e.stageAccessExpires});}
      if(action==='stage-reply'&&req.method==='POST'){const b=await body(req),u=auth(req,'stage'),validUser=u&&eventAuth(req,e,'stage'),validToken=e.stageToken&&secretEqual(b.access,e.stageToken)&&Date.now()<e.stageAccessExpires;if(!validUser&&!validToken)return send(res,401,{error:'Geen toegang'});const text=sanitize(b.text);if(!text)return send(res,400,{error:'Bericht is leeg'});const m={id:id(),slug,text,author:u?.email||'Stage',type:'stage-reply',visibility:'private',status:'private',createdAt:new Date().toISOString()};addMessage(m);broadcast(slug,'stage-reply',messageEvent(m),'moderator');return send(res,201,{message:messageEvent(m)});}
      if(action==='moderators'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Geen toegang'});return send(res,200,{users:state.users.filter(x=>e.moderators.includes(x.id)).map(safeUser)});}
      if(action==='moderators'&&req.method==='POST'){if(!mod)return send(res,401,{error:'Geen toegang'});const b=await body(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||password.length<12)return send(res,400,{error:'Vul een geldig e-mailadres en wachtwoord van minimaal 12 tekens in'});let user=state.users.find(x=>x.email===email);if(!user){user={id:id(),email,role:b.role==='stage'?'stage':'moderator',active:true,...hash(password)};state.users.push(user);}else if(!['moderator','stage'].includes(user.role))return send(res,409,{error:'Dit account heeft een andere rol'});if(!e.moderators.includes(user.id))e.moderators.push(user.id);save();return send(res,201,{user:safeUser(user)});}
      if(action==='moderators'&&req.method==='DELETE'){if(!mod)return send(res,401,{error:'Geen toegang'});const b=await body(req);e.moderators=e.moderators.filter(x=>x!==b.userId);save();return send(res,200,{ok:true});}
      if(action==='export'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Geen toegang'});const rows=state.messages.filter(m=>m.slug===slug);const csv=['tijd,type,status,naam,taal,bericht',...rows.map(m=>[m.createdAt,m.type,m.status,m.author,m.language,m.text].map(x=>'"'+String(x||'').replaceAll('"','""')+'"').join(','))].join('\n');res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="${slug}-chat.csv"`});return res.end(csv);}
      return send(res,404,{error:'Niet gevonden'});
    }
    const spa=/^\/(e|stage|moderator)\/[^/]+\/?$/.test(url.pathname);const file=path.join(__dirname,'public',url.pathname==='/'||spa?'index.html':decodeURIComponent(url.pathname).replace(/^\/+/,''));if(!file.startsWith(path.join(__dirname,'public')))return send(res,403,{error:'Forbidden'});fs.readFile(file,(err,data)=>{if(err)return send(res,404,{error:'Niet gevonden'});res.writeHead(200,{'content-type':MIME[path.extname(file)]||'application/octet-stream','cache-control':'no-cache'});res.end(data);});
  }catch(err){console.error(err);if(!res.headersSent)send(res,400,{error:err.message==='Request too large'?'Verzoek te groot':'Ongeldig verzoek'});else res.end();}
});
server.listen(PORT,'0.0.0.0',()=>console.log(`8star Chat listening on ${PORT}`));
