'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),QRCode=require('qrcode');
const PORT=Number(process.env.PORT||3000),DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data'),DATA_FILE=path.join(DATA_DIR,'state.json');
const MAX_MESSAGE=Number(process.env.MAX_MESSAGE_LENGTH||500),DEFAULT_MAX=Number(process.env.DEFAULT_MAX_USERS||10000),ROOM_RATE=Number(process.env.ROOM_PUBLISH_PER_SECOND||5);
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.json':'application/json; charset=utf-8'};
fs.mkdirSync(DATA_DIR,{recursive:true});
let state=fs.existsSync(DATA_FILE)?JSON.parse(fs.readFileSync(DATA_FILE,'utf8')):{events:[],users:[],messages:[],bans:[]};
state.events||=[];state.users||=[];state.messages||=[];state.bans||=[];
const sessions=new Map(),guestTokens=new Map(),streams=new Map(),roomRate=new Map(),userRate=new Map();let writeTimer;
const save=()=>{clearTimeout(writeTimer);writeTimer=setTimeout(()=>{const tmp=DATA_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(state));fs.renameSync(tmp,DATA_FILE);},40);};
let migrated=false;for(const e of state.events){e.blockedWords||=[];e.moderatorTopics||={};e.privateThreads||={};e.pinnedMessages||=[];if(e.privateMessagesEnabled===undefined)e.privateMessagesEnabled=true;if(!e.stageCurrentId)e.stageCurrentId='';}for(const m of state.messages){if(m.status==='stage'&&!m.stageState){m.stageState='queued';m.stageQueuedAt=m.createdAt||new Date().toISOString();if(m.type==='question'){m.status='pending';m.visibility='private';}migrated=true;}}if(migrated)save();
const id=()=>crypto.randomBytes(12).toString('hex');
const secretEqual=(a,b)=>{const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y);};
const color=(s,f)=>/^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(String(s||''))?String(s):f;
const logoUrl=s=>{try{const u=new URL(String(s||''));return u.protocol==='https:'?u.toString():'';}catch{return '';}};
const slugify=s=>String(s||'event').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'event';
const hash=(p,salt=crypto.randomBytes(16).toString('hex'))=>({salt,hash:crypto.scryptSync(p,salt,64).toString('hex')});
const safeUser=u=>({id:u.id,email:u.email,role:u.role,active:u.active!==false});
if(!state.users.some(u=>u.role==='owner')){const email=(process.env.ADMIN_EMAIL||'admin@example.com').toLowerCase(),password=process.env.ADMIN_PASSWORD;if(!password||password.length<12)throw Error('Set ADMIN_PASSWORD to a unique password of at least 12 characters.');state.users.push({id:id(),email,role:'owner',active:true,...hash(password)});save();}
function send(res,status,data,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(JSON.stringify(data));}
function cookie(req,name){const s=req.headers.cookie||'',p=s.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return p?decodeURIComponent(p.slice(name.length+1)):'';}
function auth(req,role){const sid=cookie(req,'sid'),sess=sessions.get(sid);if(!sess||sess.expires<Date.now()){if(sid)sessions.delete(sid);return null;}const u=state.users.find(x=>x.id===sess.userId&&x.active!==false);if(!u||(role==='moderator'&&!['owner','moderator','event-owner'].includes(u.role))||(role==='stage'&&!['owner','moderator','stage','event-owner'].includes(u.role)))return null;return u;}
const canManageEvent=(u,e)=>Boolean(u&&(u.role==='owner'||(u.role==='event-owner'&&u.ownerEventId===e.id)));
function eventAuth(req,e,role='moderator'){const u=auth(req,role);return u&&(u.role==='owner'||(e.moderators.includes(u.id)&&(u.role!=='event-owner'||u.ownerEventId===e.id)))?u:null;}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>30000)throw Error('Request too large');}return s?JSON.parse(s):{};}
const eventBySlug=s=>state.events.find(e=>e.slug===s);
const pinnedForEvent=e=>(e.pinnedMessages||[]).map(p=>{const m=state.messages.find(x=>x.id===p.messageId&&x.slug===e.slug&&x.status==='published'&&x.visibility==='public');return m?{...messageEvent(m),color:color(p.color,'#f0c000')}:null;}).filter(Boolean).slice(0,5);
const publicEvent=e=>({id:e.id,slug:e.slug,title:e.title,mode:e.mode,capacity:e.capacity,chatEnabled:e.chatEnabled!==false,chatTypes:e.chatTypes||'both',privateMessagesEnabled:e.privateMessagesEnabled!==false,pinnedMessages:pinnedForEvent(e),branding:{logo:e.branding?.logo||''},active:e.active,createdAt:e.createdAt});
const eventStreams=s=>{if(!streams.has(s))streams.set(s,new Set());return streams.get(s);};
function broadcast(slug,kind,data,audience='all'){const p='event: '+kind+'\ndata: '+JSON.stringify(data)+'\n\n';for(const c of eventStreams(slug))if(audience==='all'||c.role===audience||c.role==='owner'){try{c.res.write(p);}catch{}}}
function revokeUserStreams(userId,slug=''){for(const [room,connections] of streams){if(slug&&room!==slug)continue;for(const c of [...connections])if(c.userId===userId){try{c.res.write('event: access-revoked\ndata: {}\n\n');c.res.end();}catch{}connections.delete(c);}}}
function revokeUserAccess(userId){for(const [sid,session] of sessions)if(session.userId===userId)sessions.delete(sid);revokeUserStreams(userId);}
const recent=(s,n=60)=>state.messages.filter(m=>m.slug===s&&m.visibility==='public'&&m.status==='published').slice(-n);
const messageEvent=m=>({id:m.id,slug:m.slug,type:m.type,text:m.text,author:m.author,status:m.status,createdAt:m.createdAt,sourceId:m.sourceId||null,language:m.language||''});
const stageEvent=m=>({...messageEvent(m),stageState:m.stageState||'',stageQueuedAt:m.stageQueuedAt||'',stageReadAt:m.stageReadAt||''});
const stageQueue=slug=>state.messages.filter(m=>m.slug===slug&&m.stageState==='queued').map(stageEvent);
const stageSnapshot=e=>({queue:stageQueue(e.slug),current:state.messages.find(m=>m.slug===e.slug&&m.id===e.stageCurrentId&&m.stageState==='queued')?stageEvent(state.messages.find(m=>m.slug===e.slug&&m.id===e.stageCurrentId)):null});
const stageAuthorized=(req,e,access='')=>{const u=auth(req,'stage'),member=u&&eventAuth(req,e,'stage'),tokenValid=e.stageToken&&secretEqual(access,e.stageToken)&&Date.now()<e.stageAccessExpires;return Boolean(member||tokenValid);};
const countConnections=s=>[...eventStreams(s)].filter(c=>c.role==='guest').length;
function addMessage(m){state.messages.push(m);save();}
const sanitize=(s,max=MAX_MESSAGE)=>String(s||'').replace(/[<>\u0000-\u001f\u007f]/g,' ').trim().slice(0,max);
function blockedTerm(text,words){const normalized=String(text||'').normalize('NFKC').toLocaleLowerCase();return(words||[]).find(raw=>{const word=String(raw||'').trim().normalize('NFKC').toLocaleLowerCase();if(!word)return false;const escaped=word.split(/\s+/).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('\\s+');return new RegExp('(^|[^\\p{L}\\p{N}])'+escaped+'($|[^\\p{L}\\p{N}])','iu').test(normalized);});}
const assignmentEvent=m=>({id:m.id,topic:m.topic||'',assignedTo:m.assignedTo||''});
const server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://localhost');
  res.setHeader('x-content-type-options','nosniff');res.setHeader('referrer-policy','same-origin');
  res.setHeader('content-security-policy',"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; img-src 'self' data: https:; frame-ancestors "+(process.env.FRAME_ANCESTORS||'*'));
  if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type'});return res.end();}
  try{
    if(url.pathname==='/health')return send(res,200,{ok:true,connections:[...streams.values()].reduce((a,s)=>a+s.size,0),events:state.events.length});
    if(url.pathname==='/api/login'&&req.method==='POST'){const b=await body(req),email=String(b.email||'').toLowerCase(),u=state.users.find(x=>x.email===email&&x.active!==false);if(!u||!crypto.timingSafeEqual(Buffer.from(hash(String(b.password||''),u.salt).hash,'hex'),Buffer.from(u.hash,'hex')))return send(res,401,{error:'Invalid email address or password.'});const sid=id()+id();sessions.set(sid,{userId:u.id,expires:Date.now()+12*3600000});const secure=req.headers['x-forwarded-proto']==='https'?' Secure;':'';return send(res,200,{user:safeUser(u)},{'set-cookie':'sid='+sid+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200;'+secure});}
    if(url.pathname==='/api/logout'&&req.method==='POST'){sessions.delete(cookie(req,'sid'));return send(res,200,{ok:true},{'set-cookie':'sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
    if(url.pathname==='/api/me'&&req.method==='GET'){const u=auth(req);return u?send(res,200,{user:safeUser(u)}):send(res,401,{error:'Log in'});}
    if(url.pathname==='/api/events'&&req.method==='GET'){const u=auth(req);if(!u)return send(res,401,{error:'Log in'});return send(res,200,{events:state.events.filter(e=>u.role==='owner'||(e.moderators.includes(u.id)&&(u.role!=='event-owner'||u.ownerEventId===e.id))).map(publicEvent)});}
    if(url.pathname==='/api/events'&&req.method==='POST'){const u=auth(req);if(u?.role!=='owner')return send(res,403,{error:'Only the platform admin can create events.'});const b=await body(req),title=sanitize(b.title,100)||'New event';let slug=slugify(b.slug||title);if(state.events.some(e=>e.slug===slug))slug+='-'+id().slice(0,4);const e={id:id(),slug,title,mode:['moderated','readonly','open'].includes(b.mode)?b.mode:'moderated',capacity:Math.min(20000,Math.max(1,Number(b.capacity)||DEFAULT_MAX)),active:true,chatEnabled:true,chatTypes:'both',privateMessagesEnabled:true,blockedWords:[],pinnedMessages:[],privateThreads:{},branding:{primary:'#111111',background:'#ffffff',logo:logoUrl(b.logo)},createdAt:new Date().toISOString(),moderators:[u.id],moderatorTopics:{}};state.events.push(e);save();return send(res,201,{event:publicEvent(e)});}
    const match=url.pathname.match(/^\/api\/events\/([^/]+)(?:\/(.*))?$/);
    if(match){
      const slug=decodeURIComponent(match[1]),action=match[2]||'',e=eventBySlug(slug);if(!e||!e.active)return send(res,404,{error:'Event not found'});
      if(!action&&req.method==='GET')return send(res,200,{event:publicEvent(e)});
      if(action==='join'&&req.method==='POST'){const b=await body(req);if(e.chatEnabled===false)return send(res,403,{error:'Chat is disabled.'});if(countConnections(slug)>=e.capacity)return send(res,429,{error:'This chat has reached its maximum capacity.'});const participantId=String(b.participantId||'').slice(0,80);if(participantId&&state.bans.some(x=>x.slug===slug&&x.participantId===participantId))return send(res,403,{error:'You do not have access to this chat.'});const name=sanitize(b.name,40)||'Guest',token=id()+id();guestTokens.set(token,{slug,name,participantId,createdAt:Date.now()});const privateHistory=participantId?state.messages.filter(m=>m.slug===slug&&(m.participantId===participantId||m.targetParticipantId===participantId)&&['private','private-reply'].includes(m.type)):[];return send(res,200,{token,name,event:publicEvent(e),history:recent(slug),privateHistory});}
      if(action==='stream'&&req.method==='GET'){
        const token=url.searchParams.get('token')||'',guest=guestTokens.get(token),u=auth(req,'stage'),access=url.searchParams.get('access')||'',tokenValid=e.stageToken&&secretEqual(access,e.stageToken)&&Date.now()<e.stageAccessExpires;
        const stageView=url.searchParams.get('screen')==='stage';const role=guest&&guest.slug===slug?'guest':(stageView&&u&&eventAuth(req,e,'stage')?'stage':(u&&u.role!=='stage'&&eventAuth(req,e)?'moderator':(u&&eventAuth(req,e,'stage')?'stage':(tokenValid?'stage':null))));
        if(!role)return send(res,401,{error:'Session expired.'});if(role==='guest'&&countConnections(slug)>=e.capacity)return send(res,429,{error:'This chat has reached its maximum capacity.'});
        res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache, no-transform','connection':'keep-alive','x-accel-buffering':'no'});
        const history=role==='guest'?recent(slug):role==='stage'?stageQueue(slug):recent(slug);
        res.write('event: ready\ndata: '+JSON.stringify({connections:countConnections(slug),capacity:e.capacity,history,pins:pinnedForEvent(e),privateHistory:role==='guest'&&guest?.participantId?state.messages.filter(m=>m.slug===slug&&(m.participantId===guest.participantId||m.targetParticipantId===guest.participantId)&&['private','private-reply'].includes(m.type)):[],stage:role==='stage'?stageSnapshot(e):undefined})+'\n\n');
        const c={res,role,participantId:guest?.participantId,userId:u?.id||''};eventStreams(slug).add(c);const ping=setInterval(()=>{try{res.write(': ping\n\n');}catch{}},20000);req.on('close',()=>{clearInterval(ping);eventStreams(slug).delete(c);});return;
      }
      if(action==='messages'&&req.method==='POST'){
        const b=await body(req),token=String(b.token||''),g=guestTokens.get(token);if(!g||g.slug!==slug)return send(res,401,{error:'Session expired.'});
        if(e.chatEnabled===false)return send(res,403,{error:'Chat is disabled.'});if(g.participantId&&state.bans.some(x=>x.slug===slug&&x.participantId===g.participantId))return send(res,403,{error:'You do not have access to this chat.'});if(e.mode==='readonly')return send(res,403,{error:'Chat is read-only.'});
        const text=sanitize(b.text);if(!text)return send(res,400,{error:'Please enter a message first.'});if(blockedTerm(text,e.blockedWords))return send(res,400,{error:'Your message contains a blocked word or phrase.'});
        const kind=b.kind==='private'?'private':'public';if(kind==='private'&&e.privateMessagesEnabled===false)return send(res,403,{error:'Private messages are disabled for this event.'});const now=Date.now(),key=g.participantId||token,last=userRate.get(key)||0;if(now-last<5000)return send(res,429,{error:'Please wait before sending another message.'});userRate.set(key,now);
        const language=sanitize(b.language,40),direct=e.mode==='open'&&kind==='public';
        const m={id:id(),slug,text,author:g.name,participantId:g.participantId||'',type:kind==='private'?'private':'question',visibility:direct?'public':'private',status:direct?'published':kind==='private'?'private':'pending',language,createdAt:new Date().toISOString()};
        if(direct){const now=Date.now(),recentTimes=(roomRate.get(slug)||[]).filter(t=>now-t<1000);if(recentTimes.length>=ROOM_RATE)return send(res,429,{error:'This chat is busy. Please try again shortly.'});roomRate.set(slug,[...recentTimes,now]);m.publishedAt=new Date().toISOString();}
        addMessage(m);if(kind==='private'&&m.participantId){e.privateThreads||={};e.privateThreads[m.participantId]={status:'open',updatedAt:m.createdAt};save();broadcast(slug,'private-thread-status',{participantId:m.participantId,status:'open',updatedAt:m.createdAt},'moderator');}if(direct){broadcast(slug,'public',messageEvent(m));broadcast(slug,'public-message',messageEvent(m),'moderator');}else broadcast(slug,kind==='private'?'private-message':'inbox',messageEvent(m),'moderator');return send(res,201,{ok:true,status:m.status,message:messageEvent(m)});
      }
      const mod=eventAuth(req,e);
      if(action==='messages'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Access denied'});const messages=state.messages.filter(m=>m.slug===slug&&(mod.role==='owner'||canManageEvent(mod,e)||!m.assignedTo||m.assignedTo===mod.id));return send(res,200,{messages,privateThreads:e.privateThreads||{},pins:pinnedForEvent(e)});}
      if(action==='messages/topics'&&req.method==='PATCH'){if(!canManageEvent(mod,e))return send(res,403,{error:'Only the event owner can set moderator topics.'});const b=await body(req),user=state.users.find(x=>x.id===b.userId&&e.moderators.includes(x.id)&&x.role==='moderator');if(!user)return send(res,404,{error:'Moderator not found.'});const topics=[...new Set((Array.isArray(b.topics)?b.topics:[]).map(x=>sanitize(x,60)).filter(Boolean))].slice(0,20);e.moderatorTopics||={};e.moderatorTopics[user.id]=topics;save();return send(res,200,{user:{...safeUser(user),topics}});}
      if(action==='settings'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Access denied'});return send(res,200,{event:{...publicEvent(e),blockedWords:e.blockedWords||[]}});}
      if(action==='settings'&&req.method==='PATCH'){if(!mod)return send(res,401,{error:'Access denied'});const b=await body(req);if(b.title)e.title=sanitize(b.title,100);if(['open','moderated','readonly'].includes(b.mode))e.mode=b.mode;if(Number.isFinite(Number(b.capacity)))e.capacity=Math.max(1,Math.min(20000,Number(b.capacity)));if(typeof b.chatEnabled==='boolean')e.chatEnabled=b.chatEnabled;if(typeof b.privateMessagesEnabled==='boolean')e.privateMessagesEnabled=b.privateMessagesEnabled;if(['public','private','both'].includes(b.chatTypes))e.chatTypes=b.chatTypes;if(b.branding)e.branding={...e.branding,logo:logoUrl(b.branding.logo)};if(typeof b.blockedWords==='string')e.blockedWords=[...new Set(b.blockedWords.split(/[,\n]/).map(x=>sanitize(x,60)).filter(Boolean))].slice(0,100);save();broadcast(slug,'settings',publicEvent(e));return send(res,200,{event:publicEvent(e)});}
      const assign=action.match(/^messages\/([^/]+)\/assign$/);
      if(assign&&req.method==='POST'){if(!canManageEvent(mod,e))return send(res,403,{error:'Only the event owner can assign questions.'});const b=await body(req),m=state.messages.find(x=>x.id===assign[1]&&x.slug===slug);if(!m)return send(res,404,{error:'Message not found.'});const assignedTo=String(b.assignedTo||'');if(assignedTo&&!state.users.some(x=>x.id===assignedTo&&e.moderators.includes(x.id)&&x.role==='moderator'&&x.active!==false))return send(res,400,{error:'Choose an active moderator for this event.'});m.topic=sanitize(b.topic,60);m.assignedTo=assignedTo;m.assignedAt=assignedTo?new Date().toISOString():'';save();broadcast(slug,'assignment',assignmentEvent(m),'moderator');return send(res,200,{message:m});}
      if(action.startsWith('conversations/')&&req.method==='POST'){
        if(!mod)return send(res,401,{error:'Access denied'});
        const match=action.match(/^conversations\/([^/]+)\/(close|reopen)$/);if(!match)return send(res,404,{error:'Not found'});
        const participantId=decodeURIComponent(match[1]),threadMessages=state.messages.filter(m=>m.slug===slug&&(m.participantId===participantId||m.targetParticipantId===participantId)&&['private','private-reply'].includes(m.type));
        if(!threadMessages.length)return send(res,404,{error:'Private conversation not found.'});
        const status=match[2]==='close'?'closed':'open',updatedAt=new Date().toISOString();e.privateThreads||={};e.privateThreads[participantId]={...(e.privateThreads[participantId]||{}),status,updatedAt,...(status==='closed'?{closedAt:updatedAt,closedBy:mod.email}:{closedAt:'',closedBy:''})};save();broadcast(slug,'private-thread-status',{participantId,status,updatedAt},'moderator');return send(res,200,{participantId,...e.privateThreads[participantId]});
      }
      if(action==='pins'&&req.method==='POST'){
        if(!mod)return send(res,401,{error:'Access denied'});const b=await body(req),m=state.messages.find(x=>x.id===b.messageId&&x.slug===slug);
        if(!m||m.status!=='published'||m.visibility!=='public'||m.type!=='question')return send(res,400,{error:'Only published public questions can be pinned.'});
        e.pinnedMessages||=[];const existing=e.pinnedMessages.find(x=>x.messageId===m.id);if(!existing&&e.pinnedMessages.length>=5)return send(res,409,{error:'Up to five messages can be pinned at a time.'});
        const pin={messageId:m.id,color:color(b.color,'#f0c000'),by:mod.email,at:new Date().toISOString()};if(existing)Object.assign(existing,pin);else e.pinnedMessages.push(pin);save();const pins=pinnedForEvent(e);broadcast(slug,'pins',pins);return send(res,200,{pins});
      }
      const unpin=action.match(/^pins\/([^/]+)$/);if(unpin&&req.method==='DELETE'){if(!mod)return send(res,401,{error:'Access denied'});e.pinnedMessages=(e.pinnedMessages||[]).filter(x=>x.messageId!==decodeURIComponent(unpin[1]));save();const pins=pinnedForEvent(e);broadcast(slug,'pins',pins);return send(res,200,{pins});}
      if(action==='bans'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Access denied'});const bans=state.bans.filter(x=>x.slug===slug).map(b=>{const rows=state.messages.filter(m=>m.slug===slug&&m.participantId===b.participantId);return {participantId:b.participantId,name:rows[0]?.author||'Attendee',at:b.at,by:b.by,messageCount:rows.length};});return send(res,200,{bans});}
      const unban=action.match(/^bans\/([^/]+)$/);if(unban&&req.method==='DELETE'){if(!mod)return send(res,401,{error:'Access denied'});const participantId=decodeURIComponent(unban[1]);state.bans=state.bans.filter(x=>!(x.slug===slug&&x.participantId===participantId));save();broadcast(slug,'ban-change',{participantId,blocked:false},'moderator');return send(res,200,{ok:true});}
      const stageAction=action.match(/^messages\/([^/]+)\/stage-(show|read)$/);
      if(stageAction&&req.method==='POST'){
        const b=await body(req),m=state.messages.find(x=>x.id===stageAction[1]&&x.slug===slug);if(!m)return send(res,404,{error:'Message not found.'});if(!stageAuthorized(req,e,b.access))return send(res,401,{error:'Stage access required.'});if(m.stageState!=='queued')return send(res,409,{error:'This item is no longer in the speaker queue.'});
        if(stageAction[2]==='show'){e.stageCurrentId=m.id;m.stageShownAt=new Date().toISOString();}else{m.stageState='read';m.stageReadAt=new Date().toISOString();if(e.stageCurrentId===m.id)e.stageCurrentId='';}
        save();broadcast(slug,'stage-state',stageSnapshot(e),'stage');broadcast(slug,'stage-status',stageSnapshot(e),'moderator');broadcast(slug,'message-status',messageEvent(m),'moderator');return send(res,200,{message:stageEvent(m),stage:stageSnapshot(e)});
      }
      const op=action.match(/^messages\/([^/]+)\/(publish|withdraw|reject|stage|delete)$/);
      if(op&&req.method==='POST'){if(!mod)return send(res,401,{error:'Access denied'});const m=state.messages.find(x=>x.id===op[1]&&x.slug===slug);if(!m)return send(res,404,{error:'Message not found'});const act=op[2];if(act==='publish'){const now=Date.now(),recentTimes=(roomRate.get(slug)||[]).filter(t=>now-t<1000);if(recentTimes.length>=ROOM_RATE)return send(res,429,{error:'Publishing is temporarily rate-limited. Please try again shortly.'});roomRate.set(slug,[...recentTimes,now]);m.status='published';m.visibility='public';m.publishedAt=new Date().toISOString();broadcast(slug,'public',messageEvent(m));}if(act==='withdraw'){if(m.status!=='published'&&m.status!=='withdrawn')return send(res,400,{error:'Only a published question can be withdrawn.'});m.status='withdrawn';m.visibility='private';m.withdrawnAt=new Date().toISOString();broadcast(slug,'remove',{id:m.id});}if(act==='reject'){m.status='rejected';m.visibility='private';}if(act==='delete'){m.status='deleted';m.visibility='private';m.stageState='removed';if(e.stageCurrentId===m.id)e.stageCurrentId='';broadcast(slug,'remove',{id:m.id});}if(act==='withdraw'||act==='delete'){e.pinnedMessages=(e.pinnedMessages||[]).filter(x=>x.messageId!==m.id);broadcast(slug,'pins',pinnedForEvent(e));}if(act==='stage'){m.stageState='queued';m.stageQueuedAt=new Date().toISOString();m.stageReadAt='';}save();if(act==='stage')broadcast(slug,'stage-state',stageSnapshot(e),'stage');broadcast(slug,'stage-status',stageSnapshot(e),'moderator');broadcast(slug,'message-status',messageEvent(m),'moderator');return send(res,200,{message:act==='stage'?stageEvent(m):messageEvent(m)});}
      if(action==='messages/private'&&req.method==='POST'){if(!mod)return send(res,401,{error:'Access denied'});const b=await body(req),text=sanitize(b.text),participantId=String(b.participantId||'').slice(0,80),m=state.messages.find(x=>x.slug===slug&&(participantId?x.participantId===participantId:x.id===b.messageId)&&['private','question'].includes(x.type));if(!m||!m.participantId||!text)return send(res,400,{error:'This private conversation cannot be answered.'});const now=new Date().toISOString(),reply={id:id(),slug,text,author:mod.email,type:'private-reply',visibility:'private',status:'private',targetParticipantId:m.participantId,createdAt:now};addMessage(reply);e.privateThreads||={};e.privateThreads[m.participantId]={...(e.privateThreads[m.participantId]||{}),status:'open',updatedAt:now,closedAt:'',closedBy:''};save();broadcast(slug,'private-thread-status',{participantId:m.participantId,status:'open',updatedAt:now},'moderator');for(const c of eventStreams(slug))if(c.role==='guest'&&c.participantId===m.participantId)c.res.write('event: private\ndata: '+JSON.stringify(messageEvent(reply))+'\n\n');broadcast(slug,'private-reply',messageEvent(reply),'moderator');return send(res,201,{message:messageEvent(reply)});}
      if(action==='ban'&&req.method==='POST'){if(!mod)return send(res,401,{error:'Access denied'});const b=await body(req),m=state.messages.find(x=>x.id===b.messageId&&x.slug===slug);if(!m?.participantId)return send(res,400,{error:'Participant not found'});if(!state.bans.some(x=>x.slug===slug&&x.participantId===m.participantId))state.bans.push({slug,participantId:m.participantId,by:mod.email,at:new Date().toISOString()});for(const c of eventStreams(slug))if(c.role==='guest'&&c.participantId===m.participantId){try{c.res.write('event: banned\ndata: {}\n\n');c.res.end();}catch{}eventStreams(slug).delete(c);}save();broadcast(slug,'ban-change',{participantId:m.participantId,blocked:true},'moderator');return send(res,200,{ok:true});}
      if(action==='stage'&&req.method==='POST'){if(!mod)return send(res,401,{error:'Access denied'});const b=await body(req),text=sanitize(b.text);if(!text)return send(res,400,{error:'Message is empty'});const m={id:id(),slug,text,author:mod.email,type:b.type==='cue'?'cue':'stage',visibility:'private',status:'stage',stageState:'queued',stageQueuedAt:new Date().toISOString(),createdAt:new Date().toISOString()};addMessage(m);broadcast(slug,'stage-state',stageSnapshot(e),'stage');broadcast(slug,'stage-status',stageSnapshot(e),'moderator');return send(res,201,{message:stageEvent(m)});}
      if(action==='stage-access'&&req.method==='POST'){if(!canManageEvent(mod,e))return send(res,403,{error:'Only the event owner can create stage links.'});e.stageToken=crypto.randomBytes(32).toString('base64url');e.stageAccessExpires=Date.now()+12*3600000;save();return send(res,200,{url:'/stage/'+encodeURIComponent(slug)+'?access='+e.stageToken,expiresAt:e.stageAccessExpires});}
      if(action==='stage-qr'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Access denied'});const access=url.searchParams.get('access')||'';if(!e.stageToken||!secretEqual(access,e.stageToken)||Date.now()>=e.stageAccessExpires)return send(res,403,{error:'This stage link has expired. Create a new one.'});const host=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim(),proto=String(req.headers['x-forwarded-proto']||'http').split(',')[0].trim();if(!host||/[\s/]/.test(host))return send(res,400,{error:'Could not determine the public host for the QR code.'});const stageUrl=proto+'://'+host+'/stage/'+encodeURIComponent(slug)+'?access='+encodeURIComponent(access),svg=await QRCode.toString(stageUrl,{type:'svg',margin:2,width:320,errorCorrectionLevel:'M'});res.writeHead(200,{'content-type':'image/svg+xml; charset=utf-8','cache-control':'no-store'});return res.end(svg);}
      if(action==='stage-reply'&&req.method==='POST'){const b=await body(req),u=auth(req,'stage'),validUser=u&&eventAuth(req,e,'stage'),validToken=e.stageToken&&secretEqual(b.access,e.stageToken)&&Date.now()<e.stageAccessExpires;if(!validUser&&!validToken)return send(res,401,{error:'Access denied'});const text=sanitize(b.text);if(!text)return send(res,400,{error:'Message is empty'});const m={id:id(),slug,text,author:u?.email||'Speaker',type:'stage-reply',visibility:'private',status:'private',createdAt:new Date().toISOString()};addMessage(m);broadcast(slug,'stage-reply',messageEvent(m),'moderator');return send(res,201,{message:messageEvent(m)});}
      if(action==='moderators'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Access denied'});return send(res,200,{users:state.users.filter(x=>e.moderators.includes(x.id)&&(x.role!=='event-owner'||x.ownerEventId===e.id)).map(u=>({...safeUser(u),topics:e.moderatorTopics?.[u.id]||[],shared:state.events.some(other=>other.id!==e.id&&other.moderators.includes(u.id))}))});}
      if(action==='moderators'&&req.method==='POST'){if(!canManageEvent(mod,e))return send(res,403,{error:'Only the event owner can manage the team.'});const b=await body(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),requestedRole=['moderator','stage','event-owner'].includes(b.role)?b.role:'moderator';if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||password.length<12)return send(res,400,{error:'Enter a valid email address and a password of at least 12 characters.'});if(requestedRole==='event-owner'&&mod.role!=='owner')return send(res,403,{error:'Only the platform admin can create an event owner.'});let user=state.users.find(x=>x.email===email);if(!user){user={id:id(),email,role:requestedRole,active:true,...(requestedRole==='event-owner'?{ownerEventId:e.id}:{}),...hash(password)};state.users.push(user);}else if(requestedRole==='event-owner'){if(user.role!=='event-owner'||user.ownerEventId!==e.id)return send(res,409,{error:'An event owner account must be unique to this event.'});}else if(user.role!==requestedRole)return send(res,409,{error:'This account already has a different role.'});if(user.role==='owner')return send(res,409,{error:'The platform admin cannot be added as a team account.'});if(user.role==='event-owner'&&user.ownerEventId!==e.id)return send(res,409,{error:'This account belongs to another event.'});if(!e.moderators.includes(user.id))e.moderators.push(user.id);e.moderatorTopics||={};if(user.role==='moderator')e.moderatorTopics[user.id]=[...new Set(String(b.topics||'').split(',').map(x=>sanitize(x,60)).filter(Boolean))].slice(0,20);save();return send(res,201,{user:{...safeUser(user),topics:e.moderatorTopics[user.id]||[]}});}
      const teamPatch=action.match(/^moderators\/([^/]+)$/);
      if(teamPatch&&req.method==='PATCH'){
        if(!canManageEvent(mod,e))return send(res,403,{error:'Only the event owner can manage the team.'});
        const user=state.users.find(x=>x.id===decodeURIComponent(teamPatch[1])&&e.moderators.includes(x.id));if(!user)return send(res,404,{error:'Team account not found.'});
        if(user.role==='owner'||(user.role==='event-owner'&&(mod.role!=='owner'||user.ownerEventId!==e.id)))return send(res,403,{error:'This account cannot be edited here.'});
        const b=await body(req),sharedElsewhere=state.events.some(other=>other.id!==e.id&&other.moderators.includes(user.id));
        if(mod.role==='event-owner'&&sharedElsewhere&&['email','password','role','active'].some(k=>b[k]!==undefined))return send(res,403,{error:'This account is also used in another event. Ask the platform admin to change its login or access settings.'});
        if(b.email!==undefined){const email=String(b.email||'').trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))return send(res,400,{error:'Enter a valid email address.'});if(state.users.some(x=>x.id!==user.id&&x.email===email))return send(res,409,{error:'That email address is already in use.'});if(user.email!==email){user.email=email;revokeUserAccess(user.id);}}
        if(b.password){const password=String(b.password);if(password.length<12)return send(res,400,{error:'Passwords must be at least 12 characters.'});Object.assign(user,hash(password));revokeUserAccess(user.id);}
        if(b.role!==undefined){if(!['moderator','stage','event-owner'].includes(b.role))return send(res,400,{error:'Choose a valid team role.'});if(b.role==='event-owner'){if(mod.role!=='owner')return send(res,403,{error:'Only the platform admin can assign an event owner.'});const otherEvents=state.events.some(x=>x.id!==e.id&&x.moderators.includes(user.id));if(otherEvents)return send(res,409,{error:'Remove this account from its other events before making it an event owner.'});user.role='event-owner';user.ownerEventId=e.id;}else{user.role=b.role;delete user.ownerEventId;}revokeUserAccess(user.id);}
        if(typeof b.active==='boolean'&&user.active!==b.active){user.active=b.active;revokeUserAccess(user.id);}
        if(b.topics!==undefined){const values=Array.isArray(b.topics)?b.topics:String(b.topics||'').split(',');e.moderatorTopics||={};e.moderatorTopics[user.id]=[...new Set(values.map(x=>sanitize(x,60)).filter(Boolean))].slice(0,20);}
        save();return send(res,200,{user:{...safeUser(user),topics:e.moderatorTopics?.[user.id]||[]}});
      }
      if(action==='moderators'&&req.method==='DELETE'){if(!canManageEvent(mod,e))return send(res,403,{error:'Only the event owner can manage the team.'});const b=await body(req),user=state.users.find(x=>x.id===b.userId);if(!user||user.role==='owner'||(user.role==='event-owner'&&(mod.role!=='owner'||user.ownerEventId!==e.id)))return send(res,403,{error:'This account cannot be removed from the team.'});e.moderators=e.moderators.filter(x=>x!==b.userId);revokeUserStreams(b.userId,slug);if(e.moderatorTopics)delete e.moderatorTopics[b.userId];for(const m of state.messages)if(m.slug===slug&&m.assignedTo===b.userId)m.assignedTo='';save();return send(res,200,{ok:true});}
      if(action==='export'&&req.method==='GET'){if(!mod)return send(res,401,{error:'Access denied'});const rows=state.messages.filter(m=>m.slug===slug);const csv=['time,type,status,stage_status,topic,assigned_to,name,language,message',...rows.map(m=>[m.createdAt,m.type,m.status,m.stageState||'',m.topic||'',m.assignedTo||'',m.author,m.language||'',m.text].map(x=>{let v=String(x||'');if(/^[=+\-@\t\r]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"';}).join(','))].join('\n');res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="'+slug+'-chat.csv"'});return res.end(csv);}
      return send(res,404,{error:'Not found'});
    }
    const spa=/^\/(e|stage|moderator)\/[^/]+\/?$/.test(url.pathname),file=path.join(__dirname,'public',url.pathname==='/'||spa?'index.html':decodeURIComponent(url.pathname).replace(/^\/+/,''));if(!file.startsWith(path.join(__dirname,'public')))return send(res,403,{error:'Forbidden'});
    fs.readFile(file,(err,data)=>{if(err)return send(res,404,{error:'Not found'});res.writeHead(200,{'content-type':MIME[path.extname(file)]||'application/octet-stream','cache-control':'no-cache'});res.end(data);});
  }catch(err){console.error(err);if(!res.headersSent)send(res,400,{error:err.message==='Request too large'?'Request too large.':'Invalid request.'});else res.end();}
});
server.listen(PORT,'0.0.0.0',()=>console.log('8star Chat listening on '+PORT));
